# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: fplbot
# app and org for use with dashboard.serverless.com
app: fplbot-app
org: edwardjackchandler

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  liveScores:
    handler: wsgi.handler
    events:
      - http: 'GET /live_scores/{proxy+}'
  totalScores:
    handler: wsgi.handler
    events:
      - http: 'GET /live_totals/{proxy+}'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**
    - .vscode/**
    - .git-ignore

plugins:
  - serverless-python-requirements
  - serverless-wsgi